### ISSUE TITLE
How to export all topics?

### ISSUE THREAD

**Issue by wwng2333** [hikhvar/mqtt2prometheus#133]
Hello, i want to export all topics in Crazy, like Crazy/LM75, but have no idea how to configure.
```yaml
mqtt:
  server: "tcp://localhost:1883"
  client_id: "mqtt_exporter"
  topic_path: Crazy/+
  metric_per_topic_config:
    metric_name_regex: "(.*/)?(?P<metricname>.*)"
cache:
  timeout: -1
metrics:
  - prom_name: LM75
    mqtt_name: LM75
    type: gauge
  - prom_name: DS18B20
    mqtt_name: DS18B20
    type: gauge
  - prom_name: DHT11T
    mqtt_name: DHT11T
    type: gauge
  - prom_name: DHT11H
    mqtt_name: DHT11H
    type: gauge
  - prom_name: BATT
    mqtt_name: BATT
    type: gauge
```
