### ISSUE TITLE
Help needed decoding nonjson topic

### ISSUE THREAD

**Issue by RaceMouse-of-Denmark** [hikhvar/mqtt2prometheus#135]
Hi,

I have this topic: `RaceMow/wlan/rssi -63` which is not a json topic. Is it possible to decode this?
I'm subscribing to the topic `RaceMow/#` and would like to see a prom_name `RSSI` with the value `-63`. Is that at all possible with the latest version?
//Fink

**Comment by LeonidEfremov** [comment]
Same problem, no expected metrics output:

```bash
$ mosquitto_sub -h localhost -p 1883 -t /devices/yandex-weather/controls/temp     
10
```
my config:
```yaml
mqtt:
  server: tcp://localhost:1883
  client_id: mqtt_exporter
  topic_path: /devices/+/controls/+
  metric_per_topic_config:
    metric_name_regex: ^\/devices\/(?P<deviceid>.*)\/controls\/(?P<metricname>.*)$
  qos: 0
cache:
  timeout: 24h
metrics:
  - prom_name: yandex_temp
    mqtt_name: temp
    type: gauge
```
only `received_messages` metric =(
```bash
$ curl http://localhost:9641/metrics -s | grep yandex
received_messages{status="success",topic="/devices/yandex-weather/controls/condition"} 1
received_messages{status="success",topic="/devices/yandex-weather/controls/feels_like"} 1
received_messages{status="success",topic="/devices/yandex-weather/controls/humidity"} 1
received_messages{status="success",topic="/devices/yandex-weather/controls/obs_time"} 1
received_messages{status="success",topic="/devices/yandex-weather/controls/pressure_mm"} 1
received_messages{status="success",topic="/devices/yandex-weather/controls/temp"} 1
received_messages{status="success",topic="/devices/yandex-weather/controls/wind_dir"} 1
received_messages{status="success",topic="/devices/yandex-weather/controls/wind_speed"} 1
```
it seems that non-json metrics does not work at all.
