### ISSUE TITLE
container doesn't seem to start in k8s using tasmota topics

### ISSUE THREAD

**Issue by evanrich** [hikhvar/mqtt2prometheus#19]
Maybe I'm dense, but I haven't been able to get this to work for an hour now.  Can someone EILI5?

logs from the container (in kubernetes)
```
kubectl logs -f mqtt-55c8754dd6-kbls6 mqtt-exporter
2020/10/12 05:05:41 Connected to MQTT Broker.
2020/10/12 05:05:41 Will subscribe to topic tele/+/SENSOR/+
```

MQTT Lens showing topics:
![image](https://user-images.githubusercontent.com/518320/95707390-3f89c100-0c0e-11eb-8897-c2adf96de617.png)

config.yaml:
```
mqtt:
  server: tcp://localhost:1883
  topic_path: tele/+/SENSOR
  device_id_regex: "tele/(?P<deviceid>.*)/.*"
  qos: 0
cache:
  timeout: 24h
metrics:
  - prom_name: power
    mqtt_name: Power
    help: Power reading
    type: gauge
  - prom_name: voltage
    mqtt_name: Voltage
    help: Voltage Reading
    type: gauge
  - prom_name: current
    mqtt_name: Current
    help: Current Reading
    type: gauge
  - prom_name: pf
    mqtt_name: Factor
    help: Power Factor reading
    type: gauge
  - prom_name: today
    mqtt_name: Today
    help: Todays kWH usage
    type: counter
  - prom_name: yesterday
    mqtt_name: Yesterday
    help: Yesterday's kWh usage
    type: counter
  - prom_name: total
    mqtt_name: Total
    help: Total kWh usage
    type: counter
```
I'm probably doing something really stupid here, but the container just won't successfully run.

Edit 1. Ok after looking at the examples folder, I basically copied and pasted the example doc, but still doesn't start:
```
mqtt:
  server: tcp://localhost:1883
  topic_path: tele/+/SENSOR
  device_id_regex: "tele/(?P<deviceid>.*)/SENSOR"
  qos: 0
cache:
  timeout: 24h
metrics:
  # The name of the metric in prometheus
  - prom_name: consumed_energy_kilowatthours_total
    mqtt_name: "ENERGY.Total"
    help: "total measured kilowatthours since flash"
    type: counter
  - prom_name: voltage_volts
    mqtt_name: "ENERGY.Voltage"
    help: "Currently measured voltage"
    type: gauge
  - prom_name: current_amperes
    mqtt_name: "ENERGY.Current"
    help: "Currently measured current"
    type: gauge
  - prom_name: power_watts
    mqtt_name: "ENERGY.Power"
    help: "Currently measured power"
    type: gauge
  - prom_name: apparent_power_watt
    mqtt_name: "ENERGY.ApparentPower"
    help: "Currently apparent power"
    type: gauge
  - prom_name: reactive_power_watt
    mqtt_name: "ENERGY.ReactivePower"
    help: "Currently reactive power"
    type: gauge
```

Edit 2: it seems it might be related to forcing the "+" at the end?  when I use MQTT lens to look at that topic, nothing comes up:
![image](https://user-images.githubusercontent.com/518320/95708480-40702200-0c11-11eb-8d58-994205c6cbe6.png)
