### ISSUE TITLE
How to get around the one topic limit in k8s

### ISSUE THREAD

**Issue by evanrich** [hikhvar/mqtt2prometheus#21]
Not an issue, just thought I'd share this if anyone is running this in K8s like I am (at home).   Since it has an assumption of a single topic, you need to spin up multiple containers in a pod for each topic.  I did this by defining 2 seperate config files, then running on different ports (using a service monitor to have prometheus autmatically grab them.  Here's the pod definition relevant to the 2 containers, if it helps anyone:

```
- name: mqtt-exporter
        image: docker.pkg.github.com/hikhvar/mqtt2prometheus/mqtt2prometheus:v0.1.2
        volumeMounts:
        - name: dockerdata
          subPath: mqttexporter/config.yaml
          mountPath: /config.yaml
        ports:
          - name: mqtt-exporter
            containerPort: 9641
      - name: mqtt-exporter2
        image: docker.pkg.github.com/hikhvar/mqtt2prometheus/mqtt2prometheus:v0.1.2
        volumeMounts:
        - name: dockerdata
          subPath: mqttexporter/config2.yaml
          mountPath: /config.yaml
        command: ["./mqtt2prometheus"]
        args: ["-listen-port", "9642"]
        ports:
          - name: mqtt-exporter
            containerPort: 9642
```
