### ISSUE TITLE
Can't export Shelly HT, bug or configuration?

### ISSUE THREAD

**Issue by calligross** [hikhvar/mqtt2prometheus#26]
Hi!

First of all, thanks for releasing your mqtt2prometheus exporter under a OSS licence, it is much appreciated.

I'm failing to export the metrics of a Shelly HT thermometer and can't figure out, what is going wrong. Maybe you have an idea and can help?

Best regards
Calli

```yaml
mqtt:
   server: tcp://mosquitto:1883
   topic_path: shellies/shellyht-livingroom/sensor/+
   device_id_regex: "shellies/(?P<deviceid>.*)/sensor"
   qos: 0
 cache:
   timeout: 24h
 metrics:
   - prom_name: temperature
     mqtt_name: temperature
     help: DHT22 temperature reading
     type: gauge
```

```bash
Starting mqtt2prometheus ... done
Attaching to mqtt2prometheus
mqtt2prometheus    | 2020-11-06T11:31:15Z	info	mqttclient/mqttClient.go:18	Connected to MQTT Broker
mqtt2prometheus    | 2020-11-06T11:31:15Z	info	mqttclient/mqttClient.go:19	Will subscribe to topic	{"topic": "shellies/shellyht-livingroom/sensor/+"}
```

The metrics:
```bash
/ # mosquitto_sub -t "shellies/shellyht-livingroom/sensor/+" -v
shellies/shellyht-livingroom/sensor/temperature 29.12
shellies/shellyht-livingroom/sensor/humidity 41.5
shellies/shellyht-livingroom/sensor/battery 99
shellies/shellyht-livingroom/sensor/error 0
shellies/shellyht-livingroom/sensor/act_reasons ["button"]
```

The curl output:
```bash
mg@raspberrypi:~ $ curl raspberrypi:9641/metrics | grep shelly
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6629    0  6629    0     0   462k      0 --:--:-- --:--:-- --:--:--  462k
received_messages{status="success",topic="shellies/shellyht-livingroom/sensor/act_reasons"} 1
received_messages{status="success",topic="shellies/shellyht-livingroom/sensor/battery"} 1
received_messages{status="success",topic="shellies/shellyht-livingroom/sensor/error"} 1
received_messages{status="success",topic="shellies/shellyht-livingroom/sensor/humidity"} 1
received_messages{status="success",topic="shellies/shellyht-livingroom/sensor/temperature"} 1
```

**Comment by hikhvar** [comment]
Hello @calligross, 

I think you hit a limitation of the exporter. Currently the exporter expects all metrics in a single JSON object. Your shelly system uses a topic per metric. I think the exporter can support that mode too. But this needs a little rewrite. I will think about it how to support both modes, single-topic-and-json-object and topic-per-metric.

**Comment by calligross** [comment]
Thanks for the information, its good to know, that I can stop searching. :-)

It would be awesome if an adaption is doable with reasonable effort.

**Comment by hikhvar** [comment]
Hey, I wrote a first prototype to support your shelly setup. If you can test the code from the PR #27, it would be really nice!

**Comment by calligross** [comment]
Thanks so much! I just tried it out and it seems to work, if there is only one metric. As soon as I added humidity and battery, it only showed the last configured metric. But I just did a quick check, I will take a more sorrow look tomorrow.

**Comment by hikhvar** [comment]
Did you manage to take an in depth look? I could not recreate that bug in my hacking environment.

**Comment by calligross** [comment]
Sorry, that I didn't come back earlier to you. I had a quite busy week. I just took another shot. Until the changes, I had only configured the temperatures and it worked.

Now I altered the config to the following:

```yaml
 mqtt:
   server: tcp://mosquitto:1883
   topic_path: shellies/shellyht-Wohnzimmer/sensor/+
   device_id_regex: "shellies/(?P<deviceid>.*)/sensor"
   metric_per_topic_config:
     metric_name_regex: "shellies/(?P<deviceid>.*)/sensor/(?P<metricname>.*)"
   qos: 0
 cache:
   timeout: 24h
 metrics:
   - prom_name: temperature
     mqtt_name: temperature
     help: shelly temperature reading
     type: gauge
     const_labels:
       sensor_type: shelly
   - prom_name: humidity
     mqtt_name: humidity
     help: shelly humidity reading
     type: gauge
     const_labels:
       sensor_type: shelly
```

The only measurements now is the humidity value:

```bash
mg@raspberrypi:~/docker/monitoring $ curl -s http://localhost:9641/metrics | grep shellyht
humidity{sensor="shellyht-Wohnzimmer",sensor_type="shelly",topic="shellies/shellyht-Wohnzimmer/sensor/humidity"} 57 1605466031173
received_messages{status="success",topic="shellies/shellyht-Wohnzimmer/sensor/act_reasons"} 1
received_messages{status="success",topic="shellies/shellyht-Wohnzimmer/sensor/battery"} 1
received_messages{status="success",topic="shellies/shellyht-Wohnzimmer/sensor/error"} 1
received_messages{status="success",topic="shellies/shellyht-Wohnzimmer/sensor/humidity"} 1
received_messages{status="success",topic="shellies/shellyht-Wohnzimmer/sensor/temperature"} 1
```
