### ISSUE TITLE
Ability for standard web.config.file

### ISSUE THREAD

**Issue by sooslaca** [hikhvar/mqtt2prometheus#55]
Hi @hikhvar 

One last bit is missing for my setup in terms of security: is to be able to use TLS and basic auth.
Both node-exporter (https://github.com/prometheus/node_exporter) and blackbox-exporter (https://github.com/prometheus/blackbox_exporter) supports a flag called `--web.config.file` which is making it possible for end user.

In their source code I see they use
```
webConfig     = webflag.AddFlags(kingpin.CommandLine)
```
to parse up the input here.

Unfortunately I'm technically not capable to submit a PR to rewrite your code to use this parsing method hence be able to use webconfig.
Do you think you can implement this kind of flag parsing so standard flags would be available with mqtt2prometheus?

Thank you

**Comment by hikhvar** [comment]
I think it is possible. I had a look at the [library](https://github.com/prometheus/exporter-toolkit/tree/master/web) those exporters use. I think it is integrateable. However for a clean integration I need some time.

**Comment by sooslaca** [comment]
For sure, take your time ! Thank you for You for considering this one as an option !

**Comment by sooslaca** [comment]
Hi @hikhvar , you're truly awesome ! It works like a charm !
For the future users here is an example web-config.yml file
```
tls_server_config:
  # Certificate and key files for server to use to authenticate to client.
  cert_file: /certs/server.crt
  key_file: /certs/server.key

http_server_config:
  http2: true

basic_auth_users:
  username: <htpasswd style password>
```
