### ISSUE TITLE
Support for non-JSON format messages

### ISSUE THREAD

**Issue by batmule** [hikhvar/mqtt2prometheus#65]
I'm trying to parse data from a sensor that sends "raw values", like:
sensors/temperature/28E66D1B000000D4 23.4375

It does not look like that format is supported, or am I missing something? Is JSON the only supported payload format?

Regards,
Flemming

**Comment by batmule** [comment]
More detail:
2021-07-10T14:36:42+02:00       debug   metrics/ingest.go:42    Got message     {"topic": "sensors/temperature/28EEE3D31F1602D6", "payload": "18.1250"}

**Comment by hikhvar** [comment]
Hello, 

if the metrics are pure numbers you might be interested in the `metrics_per_topic_config` like in the shelly config: https://github.com/hikhvar/mqtt2prometheus/blob/master/hack/shelly.yaml

In your case I think the correct config is:
```yaml
mqtt:
  server: tcp://mosquitto:1883
  topic_path: sensors/+/+
  device_id_regex: "sensors/+/(?P<deviceid>.*)"
  metric_per_topic_config:
    metric_name_regex: "sensors/(?P<metricname>.*)/(?P<deviceid>.*)"
  qos: 0
cache:
  timeout: 24h
metrics:
  - prom_name: temperature
    # The name of the metric in a MQTT JSON message
    mqtt_name: temperature
    # The prometheus help text for this metric
    help: shelly temperature reading
    # The prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
```

This feature is rather new and undocumented :-( I currently don't have to time to document this.
