### ISSUE TITLE
is a scraper needed?

### ISSUE THREAD

**Issue by Rocco83** [hikhvar/mqtt2prometheus#80]
(again) i'm newbie of prometheus & mqtt & mqtt2prometheus

I was wondering how the mqtt2prometheus can send the data to prometheus, and found out that it's prometheus that need to scrape it.

so i've added 
```
- job_name: mqtt2prometheus
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - localhost:9641
    labels:
      alias: mqtt2prometheus
```
and guessing... where is documented that i need to add a scraper?
the closest sentence i've found is:
```
This exporter subscribes to the broker and publish the received messages as prometheus metrics. 
```
But this seems to be the other way round.

Thanks,
