### ISSUE TITLE
Relabel not working

### ISSUE THREAD

**Issue by rprata** [hikhvar/mqtt2prometheus#85]
Hi, 

I'm trying to use `relabel_configs`, similar to explained in `README.md`. The message delivery to mqtt2prometheus (/metrics):
`temperature{sensor="storage",topic="devices/workshop/storage"} 1 1655098848611`.

Follow a snippet of my prometheus.yml:
```
  - job_name: mqtt2prometheus
    static_configs:
    - targets: ['mqtt2prometheus:9641']
      labels:
        service: 'mqtt2prometheus'

    relabel_configs:
    - source_labels: ["topic"]
      target_label: location
      regex: 'devices/(.*)/.*'
      action: replace
      replacement: "$1"
```

And my config.yml:
```
mqtt:
  # The MQTT broker to connect to
  server: tcp://mosquitto:1883
  # Optional: Username and Password for authenticating with the MQTT Server
  # user: bob
  # password: happylittleclouds
  # Optional: for TLS client certificates
  # ca_cert: certs/AmazonRootCA1.pem
  # client_cert: certs/xxxxx-certificate.pem.crt
  # client_key: certs/xxxxx-private.pem.key
  # Optional: Used to specify ClientID. The default is <hostname>-<pid>
  # client_id: somedevice
  # The Topic path to subscribe to. Be aware that you have to specify the wildcard.
  topic_path: devices/+/#
  # Optional: Regular expression to extract the device ID from the topic path. The default regular expression, assumes
  # that the last "element" of the topic_path is the device id.
  # The regular expression must contain a named capture group with the name deviceid
  # For example the expression for tasamota based sensors is "tele/(?P<deviceid>.*)/.*"
  # device_id_regex: "(.*/)?(?P<deviceid>.*)"
  # The MQTT QoS level
  qos: 0
cache:
  # Timeout. Each received metric will be presented for this time if no update is send via MQTT.
  # Set the timeout to -1 to disable the deletion of metrics from the cache. The exporter presents the ingest timestamp
  # to prometheus.
  timeout: 24h
json_parsing:
  # Separator. Used to split path to elements when accessing json fields.
  # You can access json fields with dots in it. F.E. {"key.name": {"nested": "value"}}
  # Just set separator to -> and use key.name->nested as mqtt_name
  separator: .
# This is a list of valid metrics. Only metrics listed here will be exported
metrics:
  - prom_name: temperature
    mqtt_name: temperature
    help: Device temperature
    type: gauge
```

I'm using latest stable version for prometheus and mqtt2prometheus.

**Comment by rprata** [comment]
I found the problem. I updated `relabel_configs`:
````
    relabel_configs:
    - source_labels: [ topic ]
      target_label: location
      regex: "devices/(.*)/.*"
      action: replace
```

Sorry for the inconvenience.

**Comment by m-rtijn** [comment]
I think I had the same issue as you, but it only worked if I used the `metric_relabel_config`:

```
    metric_relabel_configs:
      - source_labels: [ topic ]
        target_label: location
        regex: "/sensors/(.*)/.*"
        action: replace
        replacement: "$1"
```
