### ISSUE TITLE
ghcr.io/hikhvar/mqtt2prometheus:v0.1.7-rc1 config file loading error

### ISSUE THREAD

**Issue by rolinux** [hikhvar/mqtt2prometheus#89]
Looks like `ghcr.io/hikhvar/mqtt2prometheus:v0.1.7-rc1` triggers the following error:

```
2022-08-24T12:06:46Z	fatal	cmd/mqtt2prometheus.go:80	Could not load config	{"error": "open config.yaml: no such file or directory"}
main.main
	/home/runner/work/mqtt2prometheus/mqtt2prometheus/cmd/mqtt2prometheus.go:80
runtime.main
	/opt/hostedtoolcache/go/1.19.0/x64/src/runtime/proc.go:250
```

Moving from `latest` to `v0.1.6` image tag solved the problem.

I can help with further debug but the config file should be there as the helm chart didn't change.

Thank you,
Radu

**Comment by hikhvar** [comment]
Hey, 
thank you for this bug report. Since the 0.1.7-RC1 release is rather small, I think this problem is either caused by #88 or #84. Can you give me some more details how your deployment in the helm chart looks like?

**Comment by rolinux** [comment]
```yaml
# Source: mqtt2prom/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-mqtt2prom
  labels:
    helm.sh/chart: mqtt2prom-0.1.0
    app.kubernetes.io/name: mqtt2prom
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt2prom
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mqtt2prom
        app.kubernetes.io/instance: release-name
    spec:
      securityContext:
        {}
      containers:
        - args:
          - /mqtt2prometheus
          - -config
          - /data/config.yaml
          - -log-level
          - debug
          name: mqtt2prom
          image: "ghcr.io/hikhvar/mqtt2prometheus:v0.1.6"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9641
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: 
          #     port: http
          #   initialDelaySeconds: 45
          #   periodSeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: 
          #     port: http
          #   initialDelaySeconds: 45
          #   periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
          - name: mqtt2prom-config-secret-volume
            mountPath: /data/config.yaml
            subPath: config.yaml
            readOnly: true
      volumes:
      - name: mqtt2prom-config-secret-volume
        secret:
          secretName: mqtt2prom-config-secret
```

The config comes from a secret as the MQTT is password protected.
